import { Hono } from "hono";
import type { Env, Variables } from "./env";
import { requireAuth, requestContext } from "./lib/auth";
import { jsonError } from "./lib/http";
import { consumeQueue } from "./queue";
import { allegations } from "./routes/allegations";
import { chronology } from "./routes/chronology";
import { contradictions } from "./routes/contradictions";
import { deletion } from "./routes/deletion";
import { deltaEvaluations } from "./routes/delta-evaluations";
import { deltaMatching } from "./routes/delta-matching";
import { documents } from "./routes/documents";
import { entities } from "./routes/entities";
import { evidence } from "./routes/evidence";
import { events } from "./routes/events";
import { facts } from "./routes/facts";
import { filingDeltas } from "./routes/filing-deltas";
import { filingVersions } from "./routes/filing-versions";
import { internal } from "./routes/internal";
import { matrix } from "./routes/matrix";
import { matterMemory } from "./routes/matter-memory";
import { matterOverviews } from "./routes/matter-overviews";
import { matters } from "./routes/matters";
import { narrativeSupport } from "./routes/narrative-support";
import { responsePlanning } from "./routes/response-planning";
import { responses } from "./routes/responses";
import { sources } from "./routes/sources";
import { uploads } from "./routes/uploads";

const app = new Hono<{ Bindings: Env; Variables: Variables }>();
app.use("*", requestContext);
app.onError((error, c) => jsonError(c, error));
app.get("/healthz", (c) => c.json({ status: "ok", phase: "5c", production_use_allowed: false }));
app.route("/internal", internal);
app.use("/api/*", requireAuth);
app.get("/api/me", (c) => c.json({ data: c.get("user") }));
app.route("/api/matters", matters);
app.route("/api", uploads);
app.route("/api", sources);
app.route("/api", deletion);
app.route("/api", documents);
app.route("/api", entities);
app.route("/api", facts);
app.route("/api", events);
app.route("/api", chronology);
app.route("/api", allegations);
app.route("/api", responses);
app.route("/api", evidence);
app.route("/api", contradictions);
app.route("/api", matrix);
app.route("/api", filingVersions);
app.route("/api", deltaMatching);
app.route("/api", filingDeltas);
app.route("/api", matterMemory);
app.route("/api", deltaEvaluations);
app.route("/api", narrativeSupport);
app.route("/api", matterOverviews);
app.route("/api", responsePlanning);

export default {
  fetch: app.fetch,
  queue: consumeQueue,
} satisfies ExportedHandler<Env, import("./env").QueuePayload>;
